package HelloModule;


/**
* HelloModule/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloModule.idl
* Saturday, May 20, 2023 11:39:47 PM IST
*/

public interface HelloOperations 
{
  String print_hello (String s);
} // interface HelloOperations
